version: '3.8'
services:
  php-apache:
    build:
      context: .
      dockerfile: etc/php8.2.11-apache-bookworm.dockerfile
      args:
        user: alexjesus
        uid: 1000
    restart: unless-stopped
    volumes:
      - ./project:/home/alexjesus/project
      #- ${HOME}/.ssh:/root/.ssh
    ports:
      - '80:80'
